# Generated by Django 3.2 on 2021-06-24 08:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('town_or_city', models.CharField(blank=True, max_length=40, null=True)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('jewel_type', models.CharField(choices=[('Pendant', 'Pendant'), ('Ring', 'Ring'), ('Other', 'Other')], default='Other', max_length=10)),
                ('notes', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
