# Generated by Django 3.2 on 2021-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0002_auto_20210624_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
