# Generated by Django 3.2 on 2021-06-24 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0004_completedcustomorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='completedCustomOrder',
        ),
    ]
