# Generated by Django 3.2 on 2021-06-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0005_delete_completedcustomorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customorder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
