# Generated by Django 3.2 on 2021-06-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_orders', '0006_customorder_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customorder',
            name='completed',
        ),
    ]
