# Generated by Django 3.2 on 2021-06-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_communitycard_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycard',
            name='website',
            field=models.URLField(max_length=254),
        ),
    ]
