# Generated by Django 3.2 on 2021-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_communitycard_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycard',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='communitycard',
            name='website',
            field=models.CharField(max_length=254),
        ),
    ]
