# Generated by Django 3.2 on 2021-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20210622_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitycard',
            name='id',
        ),
        migrations.AddField(
            model_name='communitycard',
            name='card_number',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communitycard',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='communitycard',
            name='website',
            field=models.URLField(max_length=254),
        ),
    ]
