# Generated by Django 3.2 on 2021-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20210623_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycard',
            name='description',
            field=models.TextField(max_length=254),
        ),
    ]
