# Generated by Django 3.2 on 2021-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_communitycard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitycard',
            name='description',
            field=models.TextField(max_length=110),
        ),
    ]
